//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Item
    {
        [Required]
        [RegularExpression("^[a-zA-Z]{1,20}$")]
        public string Name { get; set; }
        [Required]
        [RegularExpression("^.{1,2000}")]
        public string Description { get; set; }
        [Required]
        [Range(1,1000)]
        public int Quantity { get; set; }
        [Required]
        [Range(1,150)]
        public double Price { get; set; }
        public string ImagePath { get; set; }
    }
}
